version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  
    volumes:
      - ./logs:/app/logs
      - ./models:/app/models
      - ./certs:/app/certs
    env_file:
      - .env
    environment:
      # Database Configuration
      - POSTGRES_SERVER=${POSTGRES_SERVER}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - DATABASE_URL=${DATABASE_URL}
      
      # Security and API Keys
      - SECRET_KEY=${SECRET_KEY}
      - GOOGLE_CLOUD_PROJECT_ID=${GOOGLE_CLOUD_PROJECT_ID}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/certs/service-account-key.json
      
      # CORS Settings
      - BACKEND_CORS_ORIGINS=["http://localhost:3000","http://127.0.0.1:3000"]
    networks:
      - ai-marketing-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G

networks:
  ai-marketing-network:
    driver: bridge

volumes:
  postgres_data: 