# Fixed docker-compose.yml

services:
  api:
    image: zuko98/ai-marketing-api:latest
    container_name: ai-marketing-api
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      # Mount backend source code for hot reloading
      - ./src:/app/src:delegated
      # Mount other directories from backend
      - ./logs:/app/logs:delegated
      - ./models:/app/models:delegated
      - ./tests:/app/tests:delegated
      # FIXED: Mount the service account key file correctly
      - ./service-account-key.json:/app/service-account-key.json:ro
    env_file:
      - .env
    environment:
      # Environment
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - DEBUG=${DEBUG:-true}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      
      # Database Configuration
      - POSTGRES_SERVER=${POSTGRES_SERVER}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - DATABASE_URL=${DATABASE_URL}
      
      # Security and API Keys
      - SECRET_KEY=${SECRET_KEY}
      - GOOGLE_CLOUD_PROJECT_ID=${GOOGLE_CLOUD_PROJECT_ID}
      # FIXED: Correct path inside container
      - GOOGLE_APPLICATION_CREDENTIALS=/app/service-account-key.json
      
      # Dialogflow Configuration
      - DIALOGFLOW_LANGUAGE_CODE=${DIALOGFLOW_LANGUAGE_CODE:-en-US}
      - CHATBOT_SESSION_TIMEOUT=${CHATBOT_SESSION_TIMEOUT:-1800}
      - CHATBOT_MAX_MESSAGE_LENGTH=${CHATBOT_MAX_MESSAGE_LENGTH:-1000}
      - CHATBOT_CONFIDENCE_THRESHOLD=${CHATBOT_CONFIDENCE_THRESHOLD:-0.5}
      
      # CORS Settings
      - BACKEND_CORS_ORIGINS=["http://localhost:3000","http://127.0.0.1:3000","http://localhost:5173","http://127.0.0.1:5173"]
      
      # Python path
      - PYTHONPATH=/app/src
    networks:
      - ai-marketing-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

networks:
  ai-marketing-network:
    driver: bridge